services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - openfit-net

  openfit:
    build:
      context: ./
      dockerfile: Dockerfile
    image: openfit
    container_name: openfit
    restart: always
    env_file: .env
    environment:
      TZ: $TZ
      AUTH_TRUST_HOST: true
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      ADMIN_EMAIL: $ADMIN_EMAIL
      ADMIN_PASSWORD: $ADMIN_PASSWORD
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - openfit-net

volumes:
  postgres:

networks:
  openfit-net:
